### PR TITLE
Secure admin endpoints

### PR DESCRIPTION
**Pull request by Frlundsten**
Only logged in user that has role Admin can add schedules though schedules/new.

Alert unauthenticated users to login

Alert unauthorized users that they needto be admins

After admin sign in, a 'Logout' button is displayed

After admin sign in, an 'Admin panel' button is displayed

Admin login is redirected with a query parameter from backend so that frontend can dispatch an event based on that admin login. The dispatched event triggers header component to update a boolean which in turn changes the UI in the header. 

Admin role is saved in localstorage as 'userData' and is used to verify that only a signed in admin can reach the route '/admin'

### CODE REVIEW

**Comment by Emmelie83** [comment]
Nice job! Works fine for me, but there are some conflicts that need to be resolved, so I don't click approve yet. 
I just think the button looks a bit big, and would suggest either to name it just ADMIN or maybe use an icon, something like this: 
Screenshot 2024-10-31 192213

**Comment by Frlundsten** [comment]
> Nice job! Works fine for me, but there are some conflicts that need to be resolved, so I don't click approve yet. I just think the button looks a bit big, and would suggest either to name it just ADMIN or maybe use an icon, something like this: Screenshot 2024-10-31 192213

Added a similar icon instead of a button. I also think it looks better.

**Review by Mattan41 — APPROVED** [review]
_Nice!_

**Review by Emmelie83 — APPROVED** [review]
Nice!

**Pull request merged**
