### PR TITLE
Add animation that was removed during responsiveness update

### PR DESCRIPTION
**Pull request by Frlundsten**
The landingpage animation when mounting the view is remade since it was removed.

### CODE REVIEW

**Review by DevelopedByDanny — APPROVED** [review]
Anime

**Review by Emmelie83 — APPROVED** [review]
Oh, didn't know I did this. Sorry!

**Review by Mattan41 — APPROVED** [review]
👍

**Comment by Mattan41** [comment]
To make the background image extend all the way to the footer even if there is only one movie showing, could we classes for min-h-screen and flex-grow? Should make the movie container take up the full height of the screen.

**Pull request merged**
