### PR TITLE
add endpoint for adding rating for a Movie

### PR DESCRIPTION
**Pull request by DevelopedByDanny**
Methods for adding ratings for a movie in the database. MovieController, MovieService, and Movie changed.

Also this was a bit outside of the task im working on... i think

### CODE REVIEW

**Review by Mattan41 — COMMENTED** [review]
Nice work! 
should we add constraints to movieRating 0-5 and also that a user only can have one rating per movie?

**Comment by DevelopedByDanny** [comment]
Added handling for rating values (0-5) and that if a User makes a new rating it will update that rating, not add a new.

**Review by Mattan41 — APPROVED** [review]
Yes!

**Review by Frlundsten — APPROVED** [review]
Good job Danny!

**Pull request merged**
